CREATE DATABASE IF NOT EXISTS wholesale_platform
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE wholesale_platform;

CREATE TABLE IF NOT EXISTS product (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '商品ID',
  seller_id BIGINT NOT NULL COMMENT '卖家ID',
  name VARCHAR(100) NOT NULL COMMENT '商品名称',
  category_name VARCHAR(50) COMMENT '类目名称',
  price DECIMAL(10,2) NOT NULL COMMENT '价格',
  stock INT NOT NULL COMMENT '库存',
  min_order_quantity INT NOT NULL COMMENT '起批量',
  main_image_url VARCHAR(500) COMMENT '主图URL',
  status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT '商品上下架状态',
  audit_status VARCHAR(30) NOT NULL DEFAULT 'PENDING' COMMENT '审核状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='商品表';
